from . import obunaInline
from . import namazvaqtInline
from . import regionsInline
from . import quranInline
from . import sb_inline
from . import kb_inline
from . import Asmaul_HusnaInline
from . import duoinline
from . import namozturlarInline
